Repository EgoreTTa/MiniGame, pull requests merged in 2023-10, with the labels that each got.

#59 Добавлено комбо-атака
  Assets/Prefabs/Attacks/ComboAttack.prefab
  Assets/Prefabs/Attacks/ComboAttack.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Attacks/ComboAttackSystem.cs
  Assets/Scripts/Attacks/ComboAttackSystem.cs.meta
  Assets/Scripts/Attacks/DefaultAttackSystem.cs
  Assets/Scripts/Attacks/DefaultAttackSystem.cs.meta
  Assets/Scripts/Attacks/DefaultComboAttack.cs
  Assets/Scripts/Attacks/DefaultComboAttack.cs.meta
  Assets/Scripts/Attacks/DefaultRangeAttackSystem.cs
  Assets/Scripts/Attacks/DefaultRangeAttackSystem.cs.meta
  Assets/Scripts/Enemies/Enemy/Enemy.cs
  Assets/Scripts/Enemies/RangerEnemy/RangerEnemy.cs
  Assets/Scripts/Interfaces/IAttackSystem.cs
  Assets/Scripts/Interfaces/IAttackSystem.cs.meta
  Assets/Scripts/Player.cs
Labels: enhancement

#63 Hotfix (error script missing) (error combo attack system)
  Assets/Prefabs/RangerEnemy.prefab
  Assets/Scripts/Attacks/ComboAttackSystem.cs
Labels: bug

#61 Добавлена сцена "Главное меню" и обработчик выбора сцены.
  Assets/Prefabs/RangerEnemy.prefab
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/MainMenu.unity.meta
  Assets/Scenes/StartGame.unity
  Assets/Scenes/StartGame.unity.meta
  Assets/Scripts/MainMenu.cs
  Assets/Scripts/MainMenu.cs.meta
Labels: enhancement

#62 Добавлен переход уровней
  Assets/Scenes/StartGame.unity
  Assets/Scripts/Player.cs
  Assets/Scripts/TransitionLevel.cs
  Assets/Scripts/TransitionLevel.cs.meta
Labels: enhancement

#64 Добавлена функция выбрасывания предметов из инвентаря
  Assets/Scripts/GUI/ManagerGUI.cs
  Assets/Scripts/NoMonoBehaviour/Inventory.cs
Labels: enhancement

#65 Fix Bootle Bug
  Assets/Scripts/Enemies/RangerEnemy/Bottle.cs
Labels: bug

#69 Adding main menu
  Assets/Prefabs/GUI/MenuButton.prefab
  Assets/Prefabs/GUI/MenuButton.prefab.meta
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/StartGame1.unity
  Assets/Scenes/StartGame1.unity.meta
  Assets/Scripts/GUI/MainMenu.cs
  Assets/Scripts/GUI/MainMenu.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: gui

#71 Gui/in game menu
  Assets/Scenes/StartGame.unity
  Assets/Scripts/Enums/StatesGame.cs
  Assets/Scripts/Enums/StatesGame.cs.meta
  Assets/Scripts/GUI/ManagerGUI.cs
  Assets/Scripts/Player.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: gui

#75 Создание объекта окружения "Дверь"
  Assets/Cainos.meta
  Assets/Cainos/Pixel Art Top Down - Basic.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Plant.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Plant.png.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Player.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Player.png.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Props.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Props.png.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Shadow Plant.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Shadow Plant.png.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Shadow.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Shadow.png.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Struct.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Struct.png.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Tileset Grass.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Tileset Grass.png.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Tileset Stone Ground.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Tileset Stone Ground.png.meta
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Tileset Wall.png
  Assets/Cainos/Pixel Art Top Down - Basic/Texture/TX Tileset Wall.png.meta
  Assets/Resources/Prefabs/Environments/Door.prefab
  Assets/Resources/Prefabs/Environments/Door.prefab.meta
  Assets/Scripts/Environments/DoorEnvironment.cs
  Assets/Scripts/Environments/DoorEnvironment.cs.meta
Labels: enhancement

#77 Изменение передвижения объектов на физическую основу
  Assets/Scripts/Jerks/BaseJerk.cs
  Assets/Scripts/Jerks/DefaultJerk.cs
  Assets/Scripts/Mobs/Enemies/Enemy/Enemy.cs
  Assets/Scripts/Mobs/Enemies/Kamikaze/Kamikaze.cs
  Assets/Scripts/Mobs/Enemies/RangerEnemy/RangerEnemy.cs
  Assets/Scripts/Mobs/Player/Player.cs
  Assets/Scripts/Movements/BaseMovement.cs
  Assets/Scripts/Movements/DefaultMovement.cs
Labels: rework
