Repository EgoreTTa/MiniGame, pull requests merged in 2023-08, with the labels that each got.

#10 Feature/day time
  Assets/DayParts.cs
  Assets/DayParts.cs.meta
  Assets/DayTime.cs
  Assets/DayTime.cs.meta
  Assets/Scenes/SampleScene.unity
Labels: enhancement

#13 fix cs0534 and cs0115 for Pants.cs
  Assets/Pants.cs
Labels: bug

#12 Change formating *.cs files for resharper
  MiniGame.sln.DotSettings
Labels: refactoring

#14 Rework/mob move
  Assets/BaseMob.cs
  Assets/Enemy.cs
  Assets/Player.cs
  Assets/RangerEnemy.cs
Labels: rework

#7 Create Damage class
  Assets/Damage.cs
  Assets/Damage.cs.meta
  Assets/TypeDamage.cs
  Assets/TypeDamage.cs.meta
Labels: refactoring

#2 Feacture/base effect
  Assets/BaseEffect.cs
  Assets/BaseEffect.cs.meta
  Assets/BaseMob.cs
  Assets/HangoverEffect.cs
  Assets/HangoverEffect.cs.meta
Labels: enhancement

#4 Item/add vasilin
  Assets/BaseMob.cs
  Assets/Prefabs/Vasilin.prefab
  Assets/Prefabs/Vasilin.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Vasilin.cs
  Assets/Vasilin.cs.meta
Labels: enhancement

#8 Refactoring/take damage base mob
  Assets/BaseMob.cs
  Assets/Bottle.cs
  Assets/HangoverEffect.cs
  Assets/Player.cs
  Assets/RangerEnemy.cs
Labels: refactoring

#9 Create enemy Kamikaze
  Assets/Boyara.cs
  Assets/Kamikaze.cs
  Assets/Kamikaze.cs.meta
  Assets/Prefabs/Kamikaze.prefab
  Assets/Prefabs/Kamikaze.prefab.meta
  Assets/Scenes/SampleScene.unity
Labels: extension

#21 Feature/dash for player
  Assets/DefaultArmor.cs
  Assets/DefaultBoot.cs
  Assets/DefaultHelmet.cs
  Assets/Prefabs/Player.prefab
  Assets/Scripts/Bases/BaseMob.cs
  Assets/Scripts/DefaultAttack.cs
  Assets/Scripts/DefaultAttack.cs.meta
  Assets/Scripts/DefaultDash.cs
  Assets/Scripts/DefaultDash.cs.meta
  Assets/Scripts/Interfaces/IAttack.cs
  Assets/Scripts/Interfaces/IAttack.cs.meta
  Assets/Scripts/Interfaces/IDash.cs
  Assets/Scripts/Interfaces/IDash.cs.meta
  Assets/Scripts/Interfaces/StatesOfAttack.cs
  Assets/Scripts/Interfaces/StatesOfAttack.cs.meta
  Assets/Scripts/Interfaces/StatesOfDash.cs
  Assets/Scripts/Interfaces/StatesOfDash.cs.meta
  Assets/Scripts/Player.cs
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/CommonBurstAotSettings.json
Labels: enhancement

#27 Feature/destructible environment
  Assets/Images/Environment.meta
  Assets/Images/Environment/Large wooden box.png
  Assets/Images/Environment/Large wooden box.png.meta
  Assets/Images/Environment/Vase.png
  Assets/Images/Environment/Vase.png.meta
  Assets/Images/Environment/Wooden barrel.png
  Assets/Images/Environment/Wooden barrel.png.meta
  Assets/Images/Environment/Wooden box.png
  Assets/Images/Environment/Wooden box.png.meta
  Assets/Prefabs/Environment.meta
  Assets/Prefabs/Environment/Large wooden box.prefab
  Assets/Prefabs/Environment/Large wooden box.prefab.meta
  Assets/Prefabs/Environment/Vase.prefab
  Assets/Prefabs/Environment/Vase.prefab.meta
  Assets/Prefabs/Environment/Wooden barrel.prefab
  Assets/Prefabs/Environment/Wooden barrel.prefab.meta
  Assets/Prefabs/Environment/Wooden box.prefab
  Assets/Prefabs/Environment/Wooden box.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/DefaultAttack.cs
  Assets/Scripts/DefaultDash.cs
  Assets/Scripts/Enemys/BaseMob.cs
  Assets/Scripts/Environment.cs
  Assets/Scripts/Environment.cs.meta
  Assets/Scripts/Interfaces/IHealthSystem.cs
  Assets/Scripts/Interfaces/IHealthSystem.cs.meta
Labels: enhancement

#29 Feature/item drop system
  Assets/Resources.meta
  Assets/Resources/Bottle.prefab
  Assets/Resources/Bottle.prefab.meta
  Assets/Resources/Boyara.prefab
  Assets/Resources/Boyara.prefab.meta
  Assets/Resources/Noodles.prefab
  Assets/Resources/Noodles.prefab.meta
  Assets/Resources/Vodka.prefab
  Assets/Resources/Vodka.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Environment.cs
  Assets/Scripts/ItemDropSystem.cs
  Assets/Scripts/ItemDropSystem.cs.meta
Labels: enhancement

#30 Feature/non player character
  Assets/Prefabs/Player.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/DefaultAttack.cs
  Assets/Scripts/Enemys/BaseMob.cs
  Assets/Scripts/Interfaces/IInteraction.cs
  Assets/Scripts/Interfaces/IInteraction.cs.meta
  Assets/Scripts/NonPlayerCharacters.meta
  Assets/Scripts/NonPlayerCharacters/NonPlayerCharacter.cs
  Assets/Scripts/NonPlayerCharacters/NonPlayerCharacter.cs.meta
  Assets/Scripts/Player.cs
Labels: enhancement

#31 Bugfix/layers rigidbody
  Assets/Images/Wall.png
  Assets/Images/Wall.png.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/DefaultDash.cs
  Assets/Scripts/Environment.cs
  ProjectSettings/TagManager.asset
Labels: bug

#28 Feature/combined elemental effects
  Assets/Prefabs/Kamikaze.prefab
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/RangerEnemy.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/ElementalEffects.meta
  Assets/Scripts/ElementalEffects/BaseElementalEffect.cs
  Assets/Scripts/ElementalEffects/BaseElementalEffect.cs.meta
  Assets/Scripts/ElementalEffects/ElementalEffect1.cs
  Assets/Scripts/ElementalEffects/ElementalEffect1.cs.meta
  Assets/Scripts/ElementalEffects/ElementalEffect12.cs
  Assets/Scripts/ElementalEffects/ElementalEffect12.cs.meta
  Assets/Scripts/ElementalEffects/ElementalEffect2.cs
  Assets/Scripts/ElementalEffects/ElementalEffect2.cs.meta
  Assets/Scripts/Enemys/BaseMob.cs
Labels: enhancement

#34 Environment/trap
  Assets/Images/Trap.meta
  Assets/Images/Trap/Trap0.png
  Assets/Images/Trap/Trap0.png.meta
  Assets/Images/Trap/Trap1.png
  Assets/Images/Trap/Trap1.png.meta
  Assets/Images/Trap/Trap2.png
  Assets/Images/Trap/Trap2.png.meta
  Assets/Images/Trap/Trap3.png
  Assets/Images/Trap/Trap3.png.meta
  Assets/Images/Trap/Trap4.png
  Assets/Images/Trap/Trap4.png.meta
  Assets/Prefabs/Bottle.prefab
  Assets/Prefabs/Bottle.prefab.meta
  Assets/Prefabs/Equipment/Iron Armor.prefab
  Assets/Prefabs/Equipment/Iron Boot.prefab
  Assets/Prefabs/Equipment/Iron Helmet.prefab
  Assets/Prefabs/Kamikaze.prefab
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/RangerEnemy.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Enemys/BaseMob.cs
  Assets/Scripts/Environments.meta
  Assets/Scripts/Environments/Trap.cs
  Assets/Scripts/Environments/Trap.cs.meta
Labels: enhancement

#39 Добавлена плавная камера
  Assets/Scenes/SampleScene.unity
  Assets/SmoothCamera.cs
  Assets/SmoothCamera.cs.meta
Labels: enhancement

#42 Создание интерфейса и связи данных с UI объектами
  Assets/Scenes/GUI_Manager.unity
  Assets/Scenes/GUI_Manager.unity.meta
  Assets/Scripts/Enemies/BaseMob.cs
  Assets/Scripts/Enemies/Kamikaze/Kamikaze.cs
  Assets/Scripts/GUI.meta
  Assets/Scripts/GUI/HealthBar.cs
  Assets/Scripts/GUI/HealthBar.cs.meta
  Assets/Scripts/GUI/ManagerGUI.cs
  Assets/Scripts/GUI/ManagerGUI.cs.meta
Labels: enhancement

#43 Вынес методов из асбтракции в интерфейсы, разъединение сценариев мобов и игрока
  Assets/Scripts/Attacks/DefaultAttack.cs
  Assets/Scripts/ElementalEffects/ElementalEffect12.cs
  Assets/Scripts/ElementalEffects/ElementalEffect2.cs
  Assets/Scripts/Enemies/BaseMob.cs
  Assets/Scripts/Enemies/Enemy.cs
  Assets/Scripts/Enemies/Kamikaze/Kamikaze.cs
  Assets/Scripts/Enemies/RangerEnemy/RangerEnemy.cs
  Assets/Scripts/Interfaces/IMoveSystem.cs
  Assets/Scripts/Interfaces/IMoveSystem.cs.meta
  Assets/Scripts/Interfaces/IUsable.cs
  Assets/Scripts/Items/BaseItem.cs
  Assets/Scripts/Items/Boyara.cs
  Assets/Scripts/Items/Noodles.cs
  Assets/Scripts/Items/Pants.cs
  Assets/Scripts/Items/Vasilin.cs
  Assets/Scripts/Items/Vodka.cs
  Assets/Scripts/NoMonoBehaviour/Inventory.cs
  Assets/Scripts/Player.cs
Labels: rework

#45 Creating the Health Bar
  Assets/Images/UI.meta
  Assets/Images/UI/HealthBarCanvasImage.png
  Assets/Images/UI/HealthBarCanvasImage.png.meta
  Assets/Images/UI/HealthBarFullfillingImage.png
  Assets/Images/UI/HealthBarFullfillingImage.png.meta
  Assets/Prefabs/GUI.meta
  Assets/Prefabs/GUI/HealthBar.prefab
  Assets/Prefabs/GUI/HealthBar.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/GUI/HealthBar.cs
  Assets/Scripts/Player.cs
Labels: enhancement, gui

#44 Переделаны таймеры на использование Invoke и InvokeRepeating
  Assets/Scripts/Attacks/DefaultAttack.cs
  Assets/Scripts/Effects/HangoverEffect.cs
  Assets/Scripts/ElementalEffects/ElementalEffect1.cs
  Assets/Scripts/ElementalEffects/ElementalEffect12.cs
  Assets/Scripts/ElementalEffects/ElementalEffect2.cs
  Assets/Scripts/Enemies/Kamikaze/Kamikaze.cs
  Assets/Scripts/Jerks/DefaultJerk.cs
Labels: rework

#46 Исправление ошибки при получении урона на ловушке
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Effects/HangoverEffect.cs
  Assets/Scripts/ElementalEffects/ElementalEffect1.cs
  Assets/Scripts/ElementalEffects/ElementalEffect12.cs
  Assets/Scripts/Enemies/Kamikaze/Kamikaze.cs
  Assets/Scripts/Enemies/RangerEnemy/RangerEnemy.cs
  Assets/Scripts/Environments/Trap.cs
  Assets/Scripts/SpawnerEnemys.cs
  Assets/Scripts/SpawnerItems.cs
Labels: bug, refactoring, rework

#47 Добавлена возможность запрашивать инвентарь для вывода в GUI
  Assets/Scripts/GUI/ManagerGUI.cs
  Assets/Scripts/Player.cs
Labels: enhancement

#50 Экипировка отделена от вещей в инвентаре
  Assets/Scripts/NoMonoBehaviour/Inventory.cs
Labels: rework

#49 Добавлена возможность устанавливать элементы экипировки со стороны GUI
  Assets/Scripts/GUI/ManagerGUI.cs
Labels: enhancement
