Repository EgoreTTa/MiniGame, pull requests merged in 2023-09, with the labels that each got.

#51 Извлечена система передвижения и добавлена дефолтная реализация
  Assets/Prefabs/Abilities/DefaultAbility.prefab
  Assets/Prefabs/Kamikaze.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scripts/ElementalEffects/ElementalEffect12.cs
  Assets/Scripts/ElementalEffects/ElementalEffect2.cs
  Assets/Scripts/Enemies/BaseMob.cs
  Assets/Scripts/Enemies/Enemy.cs
  Assets/Scripts/Enemies/Kamikaze/Kamikaze.cs
  Assets/Scripts/Enemies/RangerEnemy/RangerEnemy.cs
  Assets/Scripts/Interfaces/IMoveSystem.cs
  Assets/Scripts/Items/Vasilin.cs
  Assets/Scripts/Jerks/DefaultJerk.cs
  Assets/Scripts/Movements.meta
  Assets/Scripts/Movements/DefaultMovement.cs
  Assets/Scripts/Movements/DefaultMovement.cs.meta
  Assets/Scripts/Player.cs
Labels: refactoring

#56 Исправление ошибки связанной с уничтожением предмета в инвентаре
  Assets/Scripts/GUI/ManagerGUI.cs
  Assets/Scripts/Items/Boyara.cs
  Assets/Scripts/Items/Noodles.cs
  Assets/Scripts/Items/Pants.cs
  Assets/Scripts/Items/Vasilin.cs
  Assets/Scripts/Items/Vodka.cs
  Assets/Scripts/NoMonoBehaviour/Inventory.cs
Labels: bug, rework

#52 Добавление "Огненный сет"
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Items/Boyara.cs
  Assets/Scripts/Items/Equipments/FireArmor.cs
  Assets/Scripts/Items/Equipments/FireArmor.cs.meta
  Assets/Scripts/Items/Equipments/FireBoot.cs
  Assets/Scripts/Items/Equipments/FireBoot.cs.meta
  Assets/Scripts/Items/Equipments/FireHelmet.cs
  Assets/Scripts/Items/Equipments/FireHelmet.cs.meta
  Assets/Scripts/Items/Vodka.cs
  Assets/Scripts/NoMonoBehaviour/Inventory.cs
  UpgradeLog.htm
Labels: item
